### ISSUE TITLE
Image download 

### ISSUE THREAD

**Issue by rugvedz** [07sima07/zap-images#1]
Hey we needed one change in downloading the images. Only thing is the script is not grouping by image url. Aka SELECT count(distinct image) FROM 7zap_skoda.group_parts returns 5034, so should only download 5034 images.

**Comment by ezirl** [comment]
Can you check how many images you have downloaded? The script should download unique images. SELECT count(distinct downloaded_image) FROM 7zap_skoda.group_parts or count images from file system

**Comment by rugvedz** [comment]
It looks like the script is updating the table by id. It does not actually store the image duplicates but it does attempt them all

**Comment by rugvedz** [comment]
How much time do you think it will take to make changes so that only distinct images are attempted to download?

**Comment by ezirl** [comment]
I will update the git repository within 2 days. I've been working on the 7zap scraper, so I've put off working on the picture loader.

**Comment by ezirl** [comment]
Pls try it again

**Comment by rugvedz** [comment]
Its working well now. Thanks
